### ISSUE TITLE
在其他python程序中如何调用？

### ISSUE THREAD

**Issue by Tokey-Yeung** [renweizhukov/txt2mobi3#3]
使用os..popen命令无法启动

**Comment by renweizhukov** [comment]
请参考https://github.com/renweizhukov/txt2mobi3#1-%E5%AE%89%E8%A3%85 来安装txt2mobi3 package。安装后也可以使用命令行工具`txt2mobi3_clt`来运行。

**Comment by renweizhukov** [comment]
请忽略这个commit，其应该是针对issue #4
